services:
  postgres:
    image: postgres:17-alpine
    container_name: practice_db
    environment:
      POSTGRES_DB: practice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practice-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/practice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: dqIAICtALsJc8JOpKzkklNMMadpoHOvmBOXMEFKNu0A=
      SPRING_PROFILES_ACTIVE: local
      ACCESS_EXPIRATION_MS: 900000
      REFRESH_EXPIRATION_MS: 604800000
    ports:
      - "3000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - practice_network
      - db_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --web.enable-lifecycle

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  practice_network:
    driver: bridge
  db_network:
    driver: bridge
    internal: true